Hello_test = ' this is a test for commit'
Hello_test_2 = 'this is also a test for commit'
print(Hello_test)
print(Hello_test_2)

def greet(name):
    return f"Hello, {name}!"

first_greeting = greet("Alice")
print (first_greeting)
# all this coding in python just to do some print statements??
# will need to go over


def add(a,b):
    return a + b

sum_result = add(5, 7)
print(f"The sum of 5 and 7 is: {sum_result}")

#kind of OP, maybe overkill for simple tasks

